<a href="https://www.kaggle.com/code/oscarjcc2002/iristensoflow?scriptVersionId=209121031" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/deep-learning/ex.csv
/kaggle/input/deep-learning/mushroom_cleaned.csv
/kaggle/input/deep-learning/iris.csv
/kaggle/input/deep-learning/fake_real_news/fake_real_news/True.csv
/kaggle/input/deep-learning/fake_real_news/fake_real_news/fake_or_real_news.csv
/kaggle/input/deep-learning/fake_real_news/fake_real_news/Fake.csv
/kaggle/input/deep-learning/eyes/MMU-Iris-Database/ReadMe.txt
/kaggle/input/deep-learning/eyes/MMU-Iris-Database/7/right/chualsr2.bmp
/kaggle/input/deep-learning/eyes/MMU-Iris-Database/7/right/chualsr3.bmp
/kaggle/input/deep-learning/eyes/MMU-Iris-Database/7/right/chualsr5.bmp
/kaggle/input/deep-learning/eyes/MMU-Iris-Database/7/right/chualsr1.bmp
/kaggle/input/deep-learning/eyes/MMU-Iris-Database/7/right/chualsr4.bmp
/kaggle/input/deep-learning/eyes/MMU-Iris-Database/7/left/chualsl4.bmp
/kaggle/input/deep-learning/eyes/MMU-Iris-Database/7/left/chualsl3.bmp
/kaggle/input/deep-learning/eyes/MMU-Iris-Database/7/left/chualsl5.bmp
/kaggle/input/deep-learning/ey

In [2]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [3]:
dataFile="/kaggle/input/deep-learning/iris.csv"
df = pd.read_csv(dataFile)
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [4]:
X = df.iloc[:,0:4].values
#y = df.iloc[:,4].values
y=df['variety']
print(y)

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object


In [5]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [6]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
print(y1)
Y = pd.get_dummies(y1).values
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[[ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
print(X_train[0:5])
print(y_train.shape)

[[6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.2]]
(120, 3)


In [8]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
  ])
model

<Sequential name=sequential, built=False>

In [9]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [10]:
model.fit(X_train, y_train, batch_size=50, epochs=100)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.3300 - loss: 1.5921
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3108 - loss: 1.4322 
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3358 - loss: 1.3425 
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1842 - loss: 1.3091 
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1458 - loss: 1.2498 
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0317 - loss: 1.2310 
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0342 - loss: 1.1903 
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0225 - loss: 1.1711 
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0458 - loss: 1.1465 
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0792 - loss: 1.1228 
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2217 - loss: 1.0990 
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2633 - loss

In [11]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.4038727581501007
Test accuracy: 0.800000011920929


In [12]:
y_pred = model.predict(X_test)
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step


array([[0.01015306, 0.23700173, 0.7528452 ],
       [0.01659711, 0.5115064 , 0.47189647],
       [0.9851157 , 0.01062173, 0.00426257],
       [0.002225  , 0.29586163, 0.7019133 ],
       [0.9523267 , 0.03781565, 0.00985764],
       [0.00663297, 0.2199391 , 0.7734279 ],
       [0.97156614, 0.02044552, 0.00798832],
       [0.02147655, 0.47204888, 0.50647455],
       [0.01116065, 0.44895336, 0.539886  ],
       [0.03914763, 0.51278037, 0.448072  ],
       [0.00617843, 0.38287872, 0.61094296],
       [0.04109003, 0.48122364, 0.4776863 ],
       [0.0218039 , 0.51155764, 0.4666385 ],
       [0.01554355, 0.43153644, 0.55292   ],
       [0.0235602 , 0.4700065 , 0.5064333 ],
       [0.96464795, 0.02731889, 0.00803322],
       [0.02863899, 0.45096576, 0.5203952 ],
       [0.02986265, 0.49471268, 0.47542456],
       [0.92051524, 0.06233898, 0.01714568],
       [0.98449916, 0.01028833, 0.00521232],
       [0.01533409, 0.28819484, 0.69647104],
       [0.04461162, 0.4623344 , 0.49305394],
       [0.

In [13]:
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual:    {actual}")
print(f"Predicted: {predicted}")

Actual:    [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
Predicted: [2 1 0 2 0 2 0 2 2 1 2 1 1 2 2 0 2 1 0 0 2 2 0 0 2 0 0 1 1 0]


In [14]:
directory = "/kaggle/working/BestModelMainTensorFlow"
BestModelMainTensorFlow_json = model.to_json()
with open(directory+'.json', "w") as json_file:
    json_file.write(BestModelMainTensorFlow_json)
model.save(directory+'.h5')
print("\nSaved Model BestModelMainTensorFlow to Disk")


Saved Model BestModelMainTensorFlow to Disk


In [15]:
from keras.models import load_model
Bestmodel = load_model("/kaggle/input/deep-learning-modelos/BestModelMainTensorFlow.h5")
Bestmodel

<Sequential name=sequential, built=True>

In [16]:
loss, accuracy = Bestmodel.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.339977890253067
Test accuracy: 0.9666666388511658


In [17]:
Newmodel = load_model("/kaggle/working/BestModelMainTensorFlow.h5")
Newmodel

<Sequential name=sequential, built=True>

In [18]:
loss, accuracy = Newmodel.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.4038727581501007
Test accuracy: 0.800000011920929
